const express = require('express');
const multer = require('multer');
const path = require('path');
const { createPost, getPosts, deletePost } = require('../controllers/lostFoundController');
const { protect } = require('../middleware/authMiddleware');
const router = express.Router();
const storage = multer.diskStorage({ destination: (req, file, cb) => cb(null, 'uploads/'), filename: (req, file, cb) => cb(null, Date.now() + path.extname(file.originalname)) });
const upload = multer({ storage });
router.post('/', upload.single('image'), protect, createPost);
router.get('/', getPosts);
router.delete('/:id', protect, deletePost);
module.exports = router;